version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: habrdb
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
    networks:
      - keycloak-network
volumes:
  postgres_data:
    driver: local