stages:
  - build
  - publish
  - deploy

build:
  stage: build
  image: maven:3.9.8
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: publish
  image: docker:27.0.3
  services:
    - docker:dind
  script:
    - docker build -t internship-library-project:latest .
    - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.intabia.ru
    - docker tag internship-library-project:latest registry.intabia.ru/internship-library-project/library:latest
    - docker push registry.intabia.ru/internship-library-project/library:latest
deploy:
  stage: deploy
  script:
    - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.intabia.ru
    - docker pull internship-library-project:latest
    - ./run_tests.sh internship vCVdRyW9
