stages:
  - build

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t library-spring-app
    - docker login -u m.kuzmin -p PrewarGlassOfWhiskey2024 https://registry.intabia.ru/harbor/projects/62/repositories
    - docker tag library-spring-app https://registry.intabia.ru/harbor/projects/62/repositories/library-spring-app
    - docker push https://registry.intabia.ru/harbor/projects/62/repositories/library-spring-app



