stages:
  - build
  - publish
  -
build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: publish
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t internship-library-project .
    - docker login -u docker-ci  -p qaswedfR3 registry.intabia.ru
    - docker tag internship-library-project registry.intabia.ru/internship-library-project
    - docker push registry.intabia.ru/internship-library-project




