stages:
  - build
  - publish
  - deploy
build:
  stage: build
  image: maven:3.9.8
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: publish
  image: docker:27.0.3
  services:
    - docker:dind
  script:
    - docker build -t internship-library-project:latest .
    - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.intabia.ru
    - docker tag internship-library-project:latest registry.intabia.ru/internship-library-project/library:latest
    - docker push registry.intabia.ru/internship-library-project/library:latest
deploy:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -y sshpass
  script:
    - sshpass -p vCVdRyW9 ssh internship@192.168.1.193  "docker pull internship-library-project/library:latest && docker run -d -p 80:80 internship-library-project/library:latest"
  tags:
    - docker
