stages:
  - build
  - publish

build:
  stage: build
  image: maven:3.9.8
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: publish
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t internship-library-project:latest .
    - docker login -u docker-ci -p qaswedfR3 registry.intabia.ru
    - docker tag internship-library-project:latest registry.intabia.ru/internship-library-project/library:latest
    - docker push registry.intabia.ru/internship-library-project/library:latest

