stages:
  - build
  - publish
  - deploy
build:
  stage: build
  image: maven:3.9.8
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: publish
  image: docker:27.0.3
  services:
    - docker:dind
  script:
    - docker build -t internship-library-project:latest .
    - docker login -u $HARBOR_USER -p $HARBOR_PASSWORD registry.intabia.ru
    - docker tag internship-library-project:latest registry.intabia.ru/internship-library-project/library:latest
    - docker push registry.intabia.ru/internship-library-project/library:latest
deploy:
  stage: deploy
  image: alpine:latest
  when: manual
  script:
    apk update && apk add --no-cache openssh sshpass
    sshpass -p "vCVdRyW9" ssh -o StrictHostKeyChecking=no internship@$192.168.1.193"
    docker stop library  true &&
    docker rmi registry.intabia.ru/internship-library-project/library:latest true &&
    echo "$HARBOR_PASSWORD" | docker login --username "$HARBOR_USERNAME" --password-stdin registry.intabia.ru &&
    docker pull registry.intabia.ru/internship-library-project/library:latest &&
    docker logout registry.intabia.ru &&
    docker run --name library --network library-network -p 8081:8080 --rm -d registry.intabia.ru/internship-library-project/library:latest"