stages:
  - build

build:
  stage: build
  image: maven:3.8.1
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: publish
  image: maven:3.8.1
  script:
    - mvn deploy
  when: manual

