stages:
  - build
  - publish

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: publish
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t library-spring-app .
    - docker login -u docker-ci  -p qaswedfR3 registry.intabia.ru
    - docker tag library-spring-app registry.intabia.ru/library-spring-app
    - docker push registry.intabia.ru/library-spring-app



