stages:
  - build

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install
    - mvn test

publish:
  stage: publish
  image: maven:latest
  script:
    - mvn deploy
  when: manual

artifacts:
  paths:
    - target/

