stages:
  - build

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean install
    - mvn test
  artifacts:
    paths:
      - target/
publish:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t .
    - docker login -u m.kuzmin -p PrewarGlassOfWhiskey2024 https://registry.intabia.ru/harbor/projects/62/repositories
    - docker tag .  https://registry.intabia.ru/harbor/projects/62/repositories/.
    - docker push https://registry.intabia.ru/harbor/projects/62/repositories/.
    - docker-compose up -d
  artifacts:
    paths:
    - .


