name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build application
        run: |
          mvn clean install

      - name: Check if build failed
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed"
            exit 1
          fi
