stages:
  - build
  - test
  - delivery
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      -dist/
    expire_in: 30 days
    reports:
    access: none
    name:
    expose_as:
    untracked: false
    exclude:
      -
    when: on_success