version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: habrdb
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
    networks:
      - keycloak-network
  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - 8280:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpass
    networks:
      - keycloak-network
    depends_on:
      - postgres
networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local