spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/habrdb
    username: habrpguser
    password: pgpwd4habr
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name:
      LibraryProject
  flyway:
    enabled: true
    locations: src/main/resources/v1_init_db.sql
    baselineOnMigrate: true
  config:
    activate:
      on-profile: staging

